name: Build and deploy blog

on:
  push:
    branches: [ prod ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    if: github.repository == 'pschlan/blog.cron-job.org'
    environment:
      name: prod
      url: https://blog.cron-job.org
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: "Build Site"
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    - name: Deploy to S3/CloudFront
      run: |
        aws s3 sync ./_site/ s3://$BLOG_S3_BUCKET
        aws cloudfront create-invalidation --distribution-id $BLOG_CF_DISTRIBUTION_ID --paths "/*"
      working-directory: ./
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
        BLOG_S3_BUCKET: ${{ secrets.BLOG_S3_BUCKET }}
        BLOG_CF_DISTRIBUTION_ID: ${{ secrets.BLOG_CF_DISTRIBUTION_ID }}
